name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Ensure scripts directory exists
        run: mkdir -p scripts

      - name: Make scripts executable
        run: chmod +x scripts/generate-test-schema.js

      - name: Run tests
        run: bun run test

      - name: Run linting
        run: bun run lint

      - name: Run quality check on generated code
        run: bun run quality-check
